POST http://localhost:8080/author/
Content-Type: application/json

{
 "userName": "ana"
}

###

POST http://localhost:8080/subscriber/
Content-Type: application/json

{
  "userName": "banana"
}

###

POST http://localhost:8080/document/
Content-Type: application/json

{
  "title": "1984"
}

###

PUT http://localhost:8080/author/1?userName=Frappilussvickotar
Content-Type: application/json

###

PUT http://localhost:8080/subscriber/1?userName=Sulleplisskotirr
Content-Type: application/json

###

PUT http://localhost:8080/document/1?title=Hömmelihähä
Content-Type: application/json

###

DELETE http://localhost:8080/author/1

###

DELETE http://localhost:8080/subscriber/1

###

DELETE http://localhost:8080/document/1