### GET AUTHOR BY ID

GET http://localhost:8080/author/9
Content-Type: application/json

### GET SUBSCRIBER BY ID

GET http://localhost:8080/subscriber/9
Content-Type: application/json

### GET DOCUMENT BY ID

GET http://localhost:8080/document/9
Content-Type: application/json

### GET ALL AUTHORS

GET http://localhost:8080/author/
Content-Type: application/json

### GET ALL SUBSCRIBERS

GET http://localhost:8080/subscriber/
Content-Type: application/json

### GET ALL DOCUMENTS

GET http://localhost:8080/document/
Content-Type: application/json

### CREATE AUTHOR

POST http://localhost:8080/author/
Content-Type: application/json

{
 "userName": "ana"
}

### CREATE SUBSCRIBER

POST http://localhost:8080/subscriber/
Content-Type: application/json

{
  "userName": "banana"
}

### CREATE DOCUMENT

POST http://localhost:8080/document/
Content-Type: application/json

{
  "title": "1984"
}

### UPDATE AUTHOR USERNAME

PUT http://localhost:8080/author/1?userName=Frappilussvickotar
Content-Type: application/json

### UPDATE SUBSCRIBER USERNAME

PUT http://localhost:8080/subscriber/1?userName=Sulleplisskotirr
Content-Type: application/json

### UPDATE DOCUMENT TITLE

PUT http://localhost:8080/document/1?title=Hömmelihähä
Content-Type: application/json

### DELETE AUTHOR BY ID

DELETE http://localhost:8080/author/1

### DELETE SUBSCRIBER BY ID

DELETE http://localhost:8080/subscriber/1

### DELETE DOCUMENT BY ID

DELETE http://localhost:8080/document/1